using DevProjex.Terminal.Tui;

namespace DevProjex.Terminal.Execution;

public sealed record TerminalServices(
	LocalizationService Localization,
	ProjectAnalysisService AnalysisService,
	ProjectContextPlanner ContextPlanner,
	TerminalProjectContextFactory ContextFactory,
	ProjectSourceIdentityResolver SourceIdentityResolver,
	RepositoryCacheCatalog RepositoryCacheCatalog,
	ProjectContextDocumentService ContextDocumentService,
	PreviewDocumentBuilder PreviewDocumentBuilder,
	ProjectCopyExportService ProjectCopyExportService,
	ProjectAnalysisReportWriter AnalysisReportWriter,
	IProjectProfileStore LocalProfileStore,
	PortableProjectProfileService PortableProfileService,
	ProjectSelectionResolver SelectionResolver,
	TerminalSettingsStore TerminalSettingsStore,
	ITerminalCommandSetupService TerminalCommandSetupService,
	GitTrackedModeReadinessProbe GitTrackedModeReadinessProbe,
	RecentProjectsStore RecentProjectsStore,
	IGitRepositoryService GitRepositoryService,
	IRepoCacheService RepoCacheService);
