using DevProjex.Infrastructure.ThemePresets;
using DevProjex.Infrastructure.RecentProjects;
using DevProjex.Infrastructure.Reports;

namespace DevProjex.Avalonia.Services;

public sealed record AvaloniaAppServices(
    LocalizationService Localization,
    HelpContentProvider HelpContentProvider,
    UserSettingsStore UserSettingsStore,
    ThemeSettingsStore ThemeSettingsStore,
    RecentProjectsStore RecentProjectsStore,
    RecentFolderAvailabilityService RecentFolderAvailabilityService,
    IProjectProfileStore ProjectProfileStore,
    IAppInstanceLauncher AppInstanceLauncher,
    IElevationService Elevation,
    ScanOptionsUseCase ScanOptionsUseCase,
    BuildTreeUseCase BuildTreeUseCase,
    IgnoreOptionsService IgnoreOptionsService,
    IgnoreRulesService IgnoreRulesService,
    IgnoreOwnershipAuditService IgnoreOwnershipAuditService,
    FilterOptionSelectionService FilterOptionSelectionService,
    TreeExportService TreeExportService,
    SelectedContentExportService ContentExportService,
    TreeAndContentExportService TreeAndContentExportService,
    ProjectCopyExportService ProjectCopyExportService,
    PreviewDocumentBuilder PreviewDocumentBuilder,
    RepositoryWebPathPresentationService RepositoryWebPathPresentationService,
    TextFileExportService TextFileExportService,
    IToastService ToastService,
    IIconStore IconStore,
    IGitRepositoryService GitRepositoryService,
    IRepoCacheService RepoCacheService,
    IZipDownloadService ZipDownloadService,
    IFileContentAnalyzer FileContentAnalyzer,
    ProjectAnalysisService ProjectAnalysisService,
    ITerminalCommandSetupService TerminalCommandSetupService,
    ITaskbarProgressService TaskbarProgressService,
    SessionMetricsRecorder SessionMetricsRecorder);
