<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DevProjex.StoreMediaCapture</AssemblyName>
    <RootNamespace>DevProjex.StoreMediaCapture</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Apps\Avalonia\DevProjex.Avalonia.csproj" />
  </ItemGroup>

</Project>
