using DevProjex.Terminal.Tui;
using DevProjex.Application.Secrets;

namespace DevProjex.Terminal.Execution;

public sealed record TerminalServices(
	LocalizationService Localization,
	ProjectAnalysisService AnalysisService,
	IgnoreRulesService IgnoreRulesService,
	IgnoreOptionsService IgnoreOptionsService,
	ProjectContextPlanner ContextPlanner,
	TerminalProjectContextFactory ContextFactory,
	ProjectSourceIdentityResolver SourceIdentityResolver,
	RepositoryCacheCatalog RepositoryCacheCatalog,
	ProjectContextDocumentService ContextDocumentService,
	TreeExportService TreeExportService,
	PreviewDocumentBuilder PreviewDocumentBuilder,
	ProjectCopyExportService ProjectCopyExportService,
	ProjectAnalysisReportWriter AnalysisReportWriter,
	IProjectProfileStore LocalProfileStore,
	PortableProjectProfileService PortableProfileService,
	ProjectSelectionResolver SelectionResolver,
	TerminalSettingsStore TerminalSettingsStore,
	ITerminalCommandSetupService TerminalCommandSetupService,
	GitTrackedModeReadinessProbe GitTrackedModeReadinessProbe,
	RecentWorkspacesService RecentWorkspacesService,
	RecentProjectsStore RecentProjectsStore,
	IGitRepositoryService GitRepositoryService,
	IRepoCacheService RepoCacheService,
	SecretRedactionSession SecretRedactionSession,
	CodeCompressionSession CodeCompressionSession,
	SecretRedactionOutputPreparer SecretRedactionOutputPreparer);
